### ISSUE TITLE
build failed python 3.11

### ISSUE THREAD

**Issue by esaaprillia** [AbstractUmbra/audioop#25]
@AbstractUmbra 

python 3.11

```
audioop/_audioop.c:1983:6: error: 'Py_mod_multiple_interpreters' undeclared here (not in a function)
 1983 |     {Py_mod_multiple_interpreters, Py_MOD_PER_INTERPRETER_GIL_SUPPORTED},
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
audioop/_audioop.c:1983:36: error: 'Py_MOD_PER_INTERPRETER_GIL_SUPPORTED' undeclared here (not in a function)
 1983 |     {Py_mod_multiple_interpreters, Py_MOD_PER_INTERPRETER_GIL_SUPPORTED},
      |                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
audioop/_audioop.c:1984:6: error: 'Py_mod_gil' undeclared here (not in a function)
 1984 |     {Py_mod_gil, Py_MOD_GIL_NOT_USED},
      |      ^~~~~~~~~~
audioop/_audioop.c:1984:18: error: 'Py_MOD_GIL_NOT_USED' undeclared here (not in a function)
 1984 |     {Py_mod_gil, Py_MOD_GIL_NOT_USED},
      |                  ^~~~~~~~~~~~~~~~~~~
```

**Comment by esaaprillia** [comment]
patch

```
--- a/audioop/_audioop.c
+++ b/audioop/_audioop.c
@@ -1980,8 +1980,10 @@ audioop_exec(PyObject* module)
 
 static PyModuleDef_Slot audioop_slots[] = {
     {Py_mod_exec, audioop_exec},
+#ifdef Py_GIL_DISABLED
     {Py_mod_multiple_interpreters, Py_MOD_PER_INTERPRETER_GIL_SUPPORTED},
     {Py_mod_gil, Py_MOD_GIL_NOT_USED},
+#endif
     {0, NULL}
 };
 
```

error

```
running install
running install_lib
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/wheel
creating build/bdist.linux-x86_64/wheel/audioop
copying build/lib.linux-x86_64-cpython-311/audioop/_audioop.abi3.so -> build/bdist.linux-x86_64/wheel/audioop
copying build/lib.linux-x86_64-cpython-311/audioop/__init__.py -> build/bdist.linux-x86_64/wheel/audioop
running install_egg_info
Copying audioop_lts.egg-info to build/bdist.linux-x86_64/wheel/audioop_lts-0.2.1-py3.11.egg-info
running install_scripts
Traceback (most recent call last):
  File "/home/staging_dir/hostpkg/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
    main()
  File "/home/staging_dir/hostpkg/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/staging_dir/hostpkg/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
    return _build_backend().build_wheel(wheel_directory, config_settings,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/staging_dir/hostpkg/lib/python3.11/site-packages/setuptools/build_meta.py", line 412, in build_wheel
    return self._build_with_temp_dir(['bdist_wheel'], '.whl',
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/staging_dir/hostpkg/lib/python3.11/site-packages/setuptools/build_meta.py", line 397, in _build_with_temp_dir
    self.run_setup()
  File "/home/staging_dir/hostpkg/lib/python3.11/site-packages/setuptools/build_meta.py", line 335, in run_setup
    exec(code, locals())
  File "<string>", line 23, in <module>
  File "/home/staging_dir/hostpkg/lib/python3.11/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/staging_dir/hostpkg/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/home/staging_dir/hostpkg/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/staging_dir/hostpkg/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
    self.run_command(cmd)
  File "/home/staging_dir/hostpkg/lib/python3.11/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/staging_dir/hostpkg/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/home/staging_dir/hostpkg/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 405, in run
    impl_tag, abi_tag, plat_tag = self.get_tag()
                                  ^^^^^^^^^^^^^^
  File "/home/staging_dir/hostpkg/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 355, in get_tag
    tag in supported_tags
AssertionError: would build wheel with unsupported tag ('cp313', 'abi3', 'linux_x86_64')
```

**Comment by AbstractUmbra** [comment]
Hi, thank you for the patch and work on this.

However, this module is designed for use for 3.13+, it is not necessary on 3.11 due to the `audioop` module still being present in the stdlib.
